server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - metrics
          - prometheus
  metrics:
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: SpringBoot-Demo
  profiles:
    active: dev


