server:
  server
  address:
  port: 8080
  servlet:
    context-path:
    session:
      timeout: 30m
      cookie:
        name:
        path:
        comment:
        domain:
        secure:
        http-only:
        max-age:
      persistent: false
      store-dir:
      tracking-modes:
  error:
    path: /error
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    excluded-user-agents:
  connection-timeout:
spring:
  redis:
    host:
    password:
    timeout: 10000ms
    lettuce:
      pool:
        min-idle:
        max-active:
        max-wait:
        max-idle:
