#应用配置
server:
  port: 8081 #应用端口号
  servlet:
    context-path: /  #应用host名称
spring:
  application:
    name: practice-gateway #应用名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # 根据注册中心自动注册路由，默认false 重启生效
          lowerCaseServiceId: false # 将注册表中的服务名转为小写创建路由，默认false，重启生效
      httpclient: #http连接设置
        pool:
          max-connections: 5000 #最大连接数
          #       max-life-time: 45000 #最大连接时间
          acquire-timeout: 15000 #返回时间
          max-idle-time: 10000 #最大空闲时间
#      routes: #路由配置
#        - id: user-api #路由id，需要全局统一，建议使用对应的spring.application.name
#          uri: lb://user-api   #路由到对应服务的地址
#          predicates:
#            - Path= /api/user/**/*   #断言，匹配规则，ant匹配
#          filters:
#            - name: FallbackHeaders
#              args:
#                executionExceptionTypeHeaderName: Test-Header
  redis: #redis配置
    database: 6 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    host: 127.0.0.1   # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 10 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
#    cluster: 集群
#      nodes:
#        - 127.0.0.1:6379
#        - 127.0.0.1:6380
#        - 127.0.0.1:6381
#        - 127.0.0.1:6382
#eurela注册中心集群地址
eureka:
  instance:
    prefer-ip-address: true #当微服务有使用IP进行注册时，优先使用IP进行访问
    appname: practice-gateway
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
#日志级别
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE #开启跟踪日志用于测试